#!/bin/bash
samtools faidx Homo_sapiens.faa
samtools faidx Mus_musculus.faa
samtools faidx Rattus_norvegicus.faa
samtools faidx Loxodonta_africana.faa
samtools faidx Rattus_norvegicus.faa
samtools faidx Canis_lupus_familiaris.faa
samtools faidx Monodelphis_domestica.faa
samtools faidx Sus_scrofa.faa
samtools faidx Oryctolagus_cuniculus.faa
samtools faidx Myotis_lucifugus.faa
samtools faidx Cavia_porcellus.faa
samtools faidx Pteropus_vampyrus.faa
samtools faidx Dipodomys_ordii.faa
samtools faidx Carlito_syrichta.faa
samtools faidx Vicugna_pacos.faa
samtools faidx Microcebus_murinus.faa
samtools faidx Sorex_araneus.faa
samtools faidx Otolemur_garnettii.faa
samtools faidx Felis_catus.faa
samtools faidx Dasypus_novemcinctus.faa
samtools faidx Mustela_putorius_furo.faa
samtools faidx Cricetulus_griseus.faa
samtools faidx Saimiri_boliviensis_boliviensis.faa
samtools faidx Ictidomys_tridecemlineatus.faa
samtools faidx Trichechus_manatus_latirostris.faa
samtools faidx Heterocephalus_glaber.faa
samtools faidx Bos_indicus.faa
samtools faidx Octodon_degus.faa
samtools faidx Condylura_cristata.faa
samtools faidx Chinchilla_lanigera.faa
samtools faidx Jaculus_jaculus.faa
samtools faidx Ceratotherium_simum_simum.faa
samtools faidx Ochotona_princeps.faa
samtools faidx Chrysochloris_asiatica.faa
samtools faidx Erinaceus_europaeus.faa
samtools faidx Orycteropus_afer_afer.faa
samtools faidx Bos_mutus.faa
samtools faidx Elephantulus_edwardii.faa
samtools faidx Eptesicus_fuscus.faa
samtools faidx Echinops_telfairi.faa
samtools faidx Microtus_ochrogaster.faa
samtools faidx Odobenus_rosmarus_divergens.faa
samtools faidx Pteropus_alecto.faa
samtools faidx Myotis_davidii.faa
samtools faidx Orcinus_orca.faa
samtools faidx Tupaia_chinensis.faa
samtools faidx Mesocricetus_auratus.faa
samtools faidx Leptonychotes_weddellii.faa
samtools faidx Macaca_fascicularis.faa
samtools faidx Chlorocebus_sabaeus.faa
samtools faidx Myotis_brandtii.faa
samtools faidx Lipotes_vexillifer.faa
samtools faidx Panthera_tigris_altaica.faa
samtools faidx Balaenoptera_acutorostrata_scammoni.faa
samtools faidx Peromyscus_maniculatus_bairdii.faa
samtools faidx Nannospalax_galili.faa
samtools faidx Ursus_maritimus.faa
samtools faidx Galeopterus_variegatus.faa
samtools faidx Equus_przewalskii.faa
samtools faidx Bison_bison_bison.faa
samtools faidx Camelus_bactrianus.faa
samtools faidx Camelus_dromedarius.faa
samtools faidx Colobus_angolensis_palliatus.faa
samtools faidx Mandrillus_leucophaeus.faa
samtools faidx Aotus_nancymaae.faa
samtools faidx Cercocebus_atys.faa
samtools faidx Macaca_nemestrina.faa
samtools faidx Propithecus_coquereli.faa
samtools faidx Equus_asinus.faa
samtools faidx Marmota_marmota_marmota.faa
samtools faidx Rousettus_aegyptiacus.faa
samtools faidx Miniopterus_natalensis.faa
samtools faidx Cebus_capucinus_imitator.faa
samtools faidx Manis_javanica.faa
samtools faidx Rhinopithecus_bieti.faa
samtools faidx Capra_hircus.faa
samtools faidx Panthera_pardus.faa
samtools faidx Hipposideros_armiger.faa
samtools faidx Castor_canadensis.faa
samtools faidx Ailuropoda_melanoleuca.faa
samtools faidx Phascolarctos_cinereus.faa
samtools faidx Odocoileus_virginianus_texanus.faa
samtools faidx Neomonachus_schauinslandi.faa
samtools faidx Meriones_unguiculatus.faa
samtools faidx Bos_taurus.faa
samtools faidx Enhydra_lutris_kenyoni.faa
samtools faidx Delphinapterus_leucas.faa
samtools faidx Ovis_aries.faa
samtools faidx Piliocolobus_tephrosceles.faa
samtools faidx Physeter_catodon.faa
samtools faidx Equus_caballus.faa
samtools faidx Pan_troglodytes.faa
samtools faidx Pongo_abelii.faa
samtools faidx Desmodus_rotundus.faa
samtools faidx Neophocaena_asiaeorientalis_asiaeorientalis.faa
samtools faidx Bubalus_bubalis.faa
samtools faidx Vulpes_vulpes.faa
samtools faidx Theropithecus_gelada.faa
samtools faidx Callorhinus_ursinus.faa
samtools faidx Puma_concolor.faa
samtools faidx Macaca_mulatta.faa
samtools faidx Bos_indicus_x_Bos_taurus.faa
samtools faidx Urocitellus_parryii.faa
samtools faidx Ursus_arctos_horribilis.faa
samtools faidx Cricetulus_griseus.faa
samtools faidx Marmota_flaviventris.faa
samtools faidx Lagenorhynchus_obliquidens.faa
samtools faidx Acinonyx_jubatus.faa
samtools faidx Eumetopias_jubatus.faa
samtools faidx Ornithorhynchus_anatinus.faa
samtools faidx Rhinolophus_ferrumequinum.faa
samtools faidx Phyllostomus_discolor.faa
samtools faidx Phoca_vitulina.faa
samtools faidx Peromyscus_leucopus.faa
samtools faidx Grammomys_surdaster.faa
samtools faidx Monodon_monoceros.faa
samtools faidx Suricata_suricatta.faa
samtools faidx Nomascus_leucogenys.faa
samtools faidx Globicephala_melas.faa
samtools faidx Lynx_canadensis.faa
samtools faidx Rhinopithecus_roxellana.faa
samtools faidx Gorilla_gorilla_gorilla.faa
samtools faidx Mastomys_coucha.faa
samtools faidx Phocoena_sinus.faa
samtools faidx Papio_anubis.faa
samtools faidx Callithrix_jacchus.faa
samtools faidx Sapajus_apella.faa
samtools faidx Zalophus_californianus.faa
samtools faidx Trachypithecus_francoisi.faa
samtools faidx Hylobates_moloch.faa
samtools faidx Mustela_erminea.faa
samtools faidx Camelus_ferus.faa
samtools faidx Lontra_canadensis.faa
samtools faidx Rattus_rattus.faa
samtools faidx Arvicanthis_niloticus.faa
samtools faidx Tursiops_truncatus.faa
samtools faidx Mirounga_leonina.faa
samtools faidx Fukomys_damarensis.faa
samtools faidx Canis_lupus_dingo.faa
samtools faidx Pan_paniscus.faa
samtools faidx Mus_caroli.faa
samtools faidx Mus_pahari.faa
samtools faidx Vombatus_ursinus.faa
samtools faidx Sarcophilus_harrisii.faa
