#!/bin/bash
# extraction of the selected genes
xargs samtools faidx Acinonyx_jubatus.faa < Acinonyx_jubatus.faa.faiLS.txt > Acinonyx_jubatus.LS.fasta
xargs samtools faidx Ailuropoda_melanoleuca.faa < Ailuropoda_melanoleuca.faa.faiLS.txt > Ailuropoda_melanoleuca.LS.fasta
xargs samtools faidx Aotus_nancymaae.faa < Aotus_nancymaae.faa.faiLS.txt > Aotus_nancymaae.LS.fasta
xargs samtools faidx Arvicanthis_niloticus.faa < Arvicanthis_niloticus.faa.faiLS.txt > Arvicanthis_niloticus.LS.fasta
xargs samtools faidx Balaenoptera_acutorostrata_scammoni.faa < Balaenoptera_acutorostrata_scammoni.faa.faiLS.txt > Balaenoptera_acutorostrata_scammoni.LS.fasta
xargs samtools faidx Bison_bison_bison.faa < Bison_bison_bison.faa.faiLS.txt > Bison_bison_bison.LS.fasta
xargs samtools faidx Bos_indicus.faa < Bos_indicus.faa.faiLS.txt > Bos_indicus.LS.fasta
xargs samtools faidx Bos_indicus_x_Bos_taurus.faa < Bos_indicus_x_Bos_taurus.faa.faiLS.txt > Bos_indicus_x_Bos_taurus.LS.fasta
xargs samtools faidx Bos_mutus.faa < Bos_mutus.faa.faiLS.txt > Bos_mutus.LS.fasta
xargs samtools faidx Bos_taurus.faa < Bos_taurus.faa.faiLS.txt > Bos_taurus.LS.fasta
xargs samtools faidx Bubalus_bubalis.faa < Bubalus_bubalis.faa.faiLS.txt > Bubalus_bubalis.LS.fasta
xargs samtools faidx Callithrix_jacchus.faa < Callithrix_jacchus.faa.faiLS.txt > Callithrix_jacchus.LS.fasta
xargs samtools faidx Callorhinus_ursinus.faa < Callorhinus_ursinus.faa.faiLS.txt > Callorhinus_ursinus.LS.fasta
xargs samtools faidx Camelus_bactrianus.faa < Camelus_bactrianus.faa.faiLS.txt > Camelus_bactrianus.LS.fasta
xargs samtools faidx Camelus_dromedarius.faa < Camelus_dromedarius.faa.faiLS.txt > Camelus_dromedarius.LS.fasta
xargs samtools faidx Camelus_ferus.faa < Camelus_ferus.faa.faiLS.txt > Camelus_ferus.LS.fasta
xargs samtools faidx Canis_lupus_dingo.faa < Canis_lupus_dingo.faa.faiLS.txt > Canis_lupus_dingo.LS.fasta
xargs samtools faidx Canis_lupus_familiaris.faa < Canis_lupus_familiaris.faa.faiLS.txt > Canis_lupus_familiaris.LS.fasta
xargs samtools faidx Capra_hircus.faa < Capra_hircus.faa.faiLS.txt > Capra_hircus.LS.fasta
xargs samtools faidx Carlito_syrichta.faa < Carlito_syrichta.faa.faiLS.txt > Carlito_syrichta.LS.fasta
xargs samtools faidx Castor_canadensis.faa < Castor_canadensis.faa.faiLS.txt > Castor_canadensis.LS.fasta
xargs samtools faidx Cavia_porcellus.faa < Cavia_porcellus.faa.faiLS.txt > Cavia_porcellus.LS.fasta
xargs samtools faidx Cebus_capucinus_imitator.faa < Cebus_capucinus_imitator.faa.faiLS.txt > Cebus_capucinus_imitator.LS.fasta
xargs samtools faidx Ceratotherium_simum_simum.faa < Ceratotherium_simum_simum.faa.faiLS.txt > Ceratotherium_simum_simum.LS.fasta
xargs samtools faidx Cercocebus_atys.faa < Cercocebus_atys.faa.faiLS.txt > Cercocebus_atys.LS.fasta
xargs samtools faidx Chinchilla_lanigera.faa < Chinchilla_lanigera.faa.faiLS.txt > Chinchilla_lanigera.LS.fasta
xargs samtools faidx Chlorocebus_sabaeus.faa < Chlorocebus_sabaeus.faa.faiLS.txt > Chlorocebus_sabaeus.LS.fasta
xargs samtools faidx Chrysochloris_asiatica.faa < Chrysochloris_asiatica.faa.faiLS.txt > Chrysochloris_asiatica.LS.fasta
xargs samtools faidx Colobus_angolensis_palliatus.faa < Colobus_angolensis_palliatus.faa.faiLS.txt > Colobus_angolensis_palliatus.LS.fasta
xargs samtools faidx Condylura_cristata.faa < Condylura_cristata.faa.faiLS.txt > Condylura_cristata.LS.fasta
xargs samtools faidx Cricetulus_griseus.faa < Cricetulus_griseus.faa.faiLS.txt > Cricetulus_griseus.LS.fasta
xargs samtools faidx Dasypus_novemcinctus.faa < Dasypus_novemcinctus.faa.faiLS.txt > Dasypus_novemcinctus.LS.fasta
xargs samtools faidx Delphinapterus_leucas.faa < Delphinapterus_leucas.faa.faiLS.txt > Delphinapterus_leucas.LS.fasta
xargs samtools faidx Desmodus_rotundus.faa < Desmodus_rotundus.faa.faiLS.txt > Desmodus_rotundus.LS.fasta
xargs samtools faidx Dipodomys_ordii.faa < Dipodomys_ordii.faa.faiLS.txt > Dipodomys_ordii.LS.fasta
xargs samtools faidx Echinops_telfairi.faa < Echinops_telfairi.faa.faiLS.txt > Echinops_telfairi.LS.fasta
xargs samtools faidx Elephantulus_edwardii.faa < Elephantulus_edwardii.faa.faiLS.txt > Elephantulus_edwardii.LS.fasta
xargs samtools faidx Enhydra_lutris_kenyoni.faa < Enhydra_lutris_kenyoni.faa.faiLS.txt > Enhydra_lutris_kenyoni.LS.fasta
xargs samtools faidx Eptesicus_fuscus.faa < Eptesicus_fuscus.faa.faiLS.txt > Eptesicus_fuscus.LS.fasta
xargs samtools faidx Equus_asinus.faa < Equus_asinus.faa.faiLS.txt > Equus_asinus.LS.fasta
xargs samtools faidx Equus_caballus.faa < Equus_caballus.faa.faiLS.txt > Equus_caballus.LS.fasta
xargs samtools faidx Equus_przewalskii.faa < Equus_przewalskii.faa.faiLS.txt > Equus_przewalskii.LS.fasta
xargs samtools faidx Erinaceus_europaeus.faa < Erinaceus_europaeus.faa.faiLS.txt > Erinaceus_europaeus.LS.fasta
xargs samtools faidx Eumetopias_jubatus.faa < Eumetopias_jubatus.faa.faiLS.txt > Eumetopias_jubatus.LS.fasta
xargs samtools faidx Felis_catus.faa < Felis_catus.faa.faiLS.txt > Felis_catus.LS.fasta
xargs samtools faidx Fukomys_damarensis.faa < Fukomys_damarensis.faa.faiLS.txt > Fukomys_damarensis.LS.fasta
xargs samtools faidx Galeopterus_variegatus.faa < Galeopterus_variegatus.faa.faiLS.txt > Galeopterus_variegatus.LS.fasta
xargs samtools faidx Globicephala_melas.faa < Globicephala_melas.faa.faiLS.txt > Globicephala_melas.LS.fasta
xargs samtools faidx Gorilla_gorilla_gorilla.faa < Gorilla_gorilla_gorilla.faa.faiLS.txt > Gorilla_gorilla_gorilla.LS.fasta
xargs samtools faidx Grammomys_surdaster.faa < Grammomys_surdaster.faa.faiLS.txt > Grammomys_surdaster.LS.fasta
xargs samtools faidx Heterocephalus_glaber.faa < Heterocephalus_glaber.faa.faiLS.txt > Heterocephalus_glaber.LS.fasta
xargs samtools faidx Hipposideros_armiger.faa < Hipposideros_armiger.faa.faiLS.txt > Hipposideros_armiger.LS.fasta
xargs samtools faidx Homo_sapiens.faa < Homo_sapiens.faa.faiLS.txt > Homo_sapiens.LS.fasta
xargs samtools faidx Hylobates_moloch.faa < Hylobates_moloch.faa.faiLS.txt > Hylobates_moloch.LS.fasta
xargs samtools faidx Ictidomys_tridecemlineatus.faa < Ictidomys_tridecemlineatus.faa.faiLS.txt > Ictidomys_tridecemlineatus.LS.fasta
xargs samtools faidx Jaculus_jaculus.faa < Jaculus_jaculus.faa.faiLS.txt > Jaculus_jaculus.LS.fasta
xargs samtools faidx Lagenorhynchus_obliquidens.faa < Lagenorhynchus_obliquidens.faa.faiLS.txt > Lagenorhynchus_obliquidens.LS.fasta
xargs samtools faidx Leptonychotes_weddellii.faa < Leptonychotes_weddellii.faa.faiLS.txt > Leptonychotes_weddellii.LS.fasta
xargs samtools faidx Lipotes_vexillifer.faa < Lipotes_vexillifer.faa.faiLS.txt > Lipotes_vexillifer.LS.fasta
xargs samtools faidx Lontra_canadensis.faa < Lontra_canadensis.faa.faiLS.txt > Lontra_canadensis.LS.fasta
xargs samtools faidx Loxodonta_africana.faa < Loxodonta_africana.faa.faiLS.txt > Loxodonta_africana.LS.fasta
xargs samtools faidx Lynx_canadensis.faa < Lynx_canadensis.faa.faiLS.txt > Lynx_canadensis.LS.fasta
xargs samtools faidx Macaca_fascicularis.faa < Macaca_fascicularis.faa.faiLS.txt > Macaca_fascicularis.LS.fasta
xargs samtools faidx Macaca_mulatta.faa < Macaca_mulatta.faa.faiLS.txt > Macaca_mulatta.LS.fasta
xargs samtools faidx Macaca_nemestrina.faa < Macaca_nemestrina.faa.faiLS.txt > Macaca_nemestrina.LS.fasta
xargs samtools faidx Mandrillus_leucophaeus.faa < Mandrillus_leucophaeus.faa.faiLS.txt > Mandrillus_leucophaeus.LS.fasta
xargs samtools faidx Manis_javanica.faa < Manis_javanica.faa.faiLS.txt > Manis_javanica.LS.fasta
xargs samtools faidx Marmota_flaviventris.faa < Marmota_flaviventris.faa.faiLS.txt > Marmota_flaviventris.LS.fasta
xargs samtools faidx Marmota_marmota_marmota.faa < Marmota_marmota_marmota.faa.faiLS.txt > Marmota_marmota_marmota.LS.fasta
xargs samtools faidx Mastomys_coucha.faa < Mastomys_coucha.faa.faiLS.txt > Mastomys_coucha.LS.fasta
xargs samtools faidx Meriones_unguiculatus.faa < Meriones_unguiculatus.faa.faiLS.txt > Meriones_unguiculatus.LS.fasta
xargs samtools faidx Mesocricetus_auratus.faa < Mesocricetus_auratus.faa.faiLS.txt > Mesocricetus_auratus.LS.fasta
xargs samtools faidx Microcebus_murinus.faa < Microcebus_murinus.faa.faiLS.txt > Microcebus_murinus.LS.fasta
xargs samtools faidx Microtus_ochrogaster.faa < Microtus_ochrogaster.faa.faiLS.txt > Microtus_ochrogaster.LS.fasta
xargs samtools faidx Miniopterus_natalensis.faa < Miniopterus_natalensis.faa.faiLS.txt > Miniopterus_natalensis.LS.fasta
xargs samtools faidx Mirounga_leonina.faa < Mirounga_leonina.faa.faiLS.txt > Mirounga_leonina.LS.fasta
xargs samtools faidx Monodelphis_domestica.faa < Monodelphis_domestica.faa.faiLS.txt > Monodelphis_domestica.LS.fasta
xargs samtools faidx Monodon_monoceros.faa < Monodon_monoceros.faa.faiLS.txt > Monodon_monoceros.LS.fasta
xargs samtools faidx Mus_caroli.faa < Mus_caroli.faa.faiLS.txt > Mus_caroli.LS.fasta
xargs samtools faidx Mus_musculus.faa < Mus_musculus.faa.faiLS.txt > Mus_musculus.LS.fasta
xargs samtools faidx Mus_pahari.faa < Mus_pahari.faa.faiLS.txt > Mus_pahari.LS.fasta
xargs samtools faidx Mustela_erminea.faa < Mustela_erminea.faa.faiLS.txt > Mustela_erminea.LS.fasta
xargs samtools faidx Mustela_putorius_furo.faa < Mustela_putorius_furo.faa.faiLS.txt > Mustela_putorius_furo.LS.fasta
xargs samtools faidx Myotis_brandtii.faa < Myotis_brandtii.faa.faiLS.txt > Myotis_brandtii.LS.fasta
xargs samtools faidx Myotis_davidii.faa < Myotis_davidii.faa.faiLS.txt > Myotis_davidii.LS.fasta
xargs samtools faidx Myotis_lucifugus.faa < Myotis_lucifugus.faa.faiLS.txt > Myotis_lucifugus.LS.fasta
xargs samtools faidx Nannospalax_galili.faa < Nannospalax_galili.faa.faiLS.txt > Nannospalax_galili.LS.fasta
xargs samtools faidx Neomonachus_schauinslandi.faa < Neomonachus_schauinslandi.faa.faiLS.txt > Neomonachus_schauinslandi.LS.fasta
xargs samtools faidx Neophocaena_asiaeorientalis_asiaeorientalis.faa < Neophocaena_asiaeorientalis_asiaeorientalis.faa.faiLS.txt > Neophocaena_asiaeorientalis_asiaeorientalis.LS.fasta
xargs samtools faidx Nomascus_leucogenys.faa < Nomascus_leucogenys.faa.faiLS.txt > Nomascus_leucogenys.LS.fasta
xargs samtools faidx Ochotona_princeps.faa < Ochotona_princeps.faa.faiLS.txt > Ochotona_princeps.LS.fasta
xargs samtools faidx Octodon_degus.faa < Octodon_degus.faa.faiLS.txt > Octodon_degus.LS.fasta
xargs samtools faidx Odobenus_rosmarus_divergens.faa < Odobenus_rosmarus_divergens.faa.faiLS.txt > Odobenus_rosmarus_divergens.LS.fasta
xargs samtools faidx Odocoileus_virginianus_texanus.faa < Odocoileus_virginianus_texanus.faa.faiLS.txt > Odocoileus_virginianus_texanus.LS.fasta
xargs samtools faidx Orcinus_orca.faa < Orcinus_orca.faa.faiLS.txt > Orcinus_orca.LS.fasta
xargs samtools faidx Ornithorhynchus_anatinus.faa < Ornithorhynchus_anatinus.faa.faiLS.txt > Ornithorhynchus_anatinus.LS.fasta
xargs samtools faidx Orycteropus_afer_afer.faa < Orycteropus_afer_afer.faa.faiLS.txt > Orycteropus_afer_afer.LS.fasta
xargs samtools faidx Oryctolagus_cuniculus.faa < Oryctolagus_cuniculus.faa.faiLS.txt > Oryctolagus_cuniculus.LS.fasta
xargs samtools faidx Otolemur_garnettii.faa < Otolemur_garnettii.faa.faiLS.txt > Otolemur_garnettii.LS.fasta
xargs samtools faidx Ovis_aries.faa < Ovis_aries.faa.faiLS.txt > Ovis_aries.LS.fasta
xargs samtools faidx Pan_paniscus.faa < Pan_paniscus.faa.faiLS.txt > Pan_paniscus.LS.fasta
xargs samtools faidx Pan_troglodytes.faa < Pan_troglodytes.faa.faiLS.txt > Pan_troglodytes.LS.fasta
xargs samtools faidx Panthera_pardus.faa < Panthera_pardus.faa.faiLS.txt > Panthera_pardus.LS.fasta
xargs samtools faidx Panthera_tigris_altaica.faa < Panthera_tigris_altaica.faa.faiLS.txt > Panthera_tigris_altaica.LS.fasta
xargs samtools faidx Papio_anubis.faa < Papio_anubis.faa.faiLS.txt > Papio_anubis.LS.fasta
xargs samtools faidx Peromyscus_leucopus.faa < Peromyscus_leucopus.faa.faiLS.txt > Peromyscus_leucopus.LS.fasta
xargs samtools faidx Peromyscus_maniculatus_bairdii.faa < Peromyscus_maniculatus_bairdii.faa.faiLS.txt > Peromyscus_maniculatus_bairdii.LS.fasta
xargs samtools faidx Phascolarctos_cinereus.faa < Phascolarctos_cinereus.faa.faiLS.txt > Phascolarctos_cinereus.LS.fasta
xargs samtools faidx Phoca_vitulina.faa < Phoca_vitulina.faa.faiLS.txt > Phoca_vitulina.LS.fasta
xargs samtools faidx Phocoena_sinus.faa < Phocoena_sinus.faa.faiLS.txt > Phocoena_sinus.LS.fasta
xargs samtools faidx Phyllostomus_discolor.faa < Phyllostomus_discolor.faa.faiLS.txt > Phyllostomus_discolor.LS.fasta
xargs samtools faidx Physeter_catodon.faa < Physeter_catodon.faa.faiLS.txt > Physeter_catodon.LS.fasta
xargs samtools faidx Piliocolobus_tephrosceles.faa < Piliocolobus_tephrosceles.faa.faiLS.txt > Piliocolobus_tephrosceles.LS.fasta
xargs samtools faidx Pongo_abelii.faa < Pongo_abelii.faa.faiLS.txt > Pongo_abelii.LS.fasta
xargs samtools faidx Propithecus_coquereli.faa < Propithecus_coquereli.faa.faiLS.txt > Propithecus_coquereli.LS.fasta
xargs samtools faidx Pteropus_alecto.faa < Pteropus_alecto.faa.faiLS.txt > Pteropus_alecto.LS.fasta
xargs samtools faidx Pteropus_vampyrus.faa < Pteropus_vampyrus.faa.faiLS.txt > Pteropus_vampyrus.LS.fasta
xargs samtools faidx Puma_concolor.faa < Puma_concolor.faa.faiLS.txt > Puma_concolor.LS.fasta
xargs samtools faidx Rattus_norvegicus.faa < Rattus_norvegicus.faa.faiLS.txt > Rattus_norvegicus.LS.fasta
xargs samtools faidx Rattus_rattus.faa < Rattus_rattus.faa.faiLS.txt > Rattus_rattus.LS.fasta
xargs samtools faidx Rhinolophus_ferrumequinum.faa < Rhinolophus_ferrumequinum.faa.faiLS.txt > Rhinolophus_ferrumequinum.LS.fasta
xargs samtools faidx Rhinopithecus_bieti.faa < Rhinopithecus_bieti.faa.faiLS.txt > Rhinopithecus_bieti.LS.fasta
xargs samtools faidx Rhinopithecus_roxellana.faa < Rhinopithecus_roxellana.faa.faiLS.txt > Rhinopithecus_roxellana.LS.fasta
xargs samtools faidx Rousettus_aegyptiacus.faa < Rousettus_aegyptiacus.faa.faiLS.txt > Rousettus_aegyptiacus.LS.fasta
xargs samtools faidx Saimiri_boliviensis_boliviensis.faa < Saimiri_boliviensis_boliviensis.faa.faiLS.txt > Saimiri_boliviensis_boliviensis.LS.fasta
xargs samtools faidx Sapajus_apella.faa < Sapajus_apella.faa.faiLS.txt > Sapajus_apella.LS.fasta
xargs samtools faidx Sarcophilus_harrisii.faa < Sarcophilus_harrisii.faa.faiLS.txt > Sarcophilus_harrisii.LS.fasta
xargs samtools faidx Sorex_araneus.faa < Sorex_araneus.faa.faiLS.txt > Sorex_araneus.LS.fasta
xargs samtools faidx Suricata_suricatta.faa < Suricata_suricatta.faa.faiLS.txt > Suricata_suricatta.LS.fasta
xargs samtools faidx Sus_scrofa.faa < Sus_scrofa.faa.faiLS.txt > Sus_scrofa.LS.fasta
xargs samtools faidx Theropithecus_gelada.faa < Theropithecus_gelada.faa.faiLS.txt > Theropithecus_gelada.LS.fasta
xargs samtools faidx Trachypithecus_francoisi.faa < Trachypithecus_francoisi.faa.faiLS.txt > Trachypithecus_francoisi.LS.fasta
xargs samtools faidx Trichechus_manatus_latirostris.faa < Trichechus_manatus_latirostris.faa.faiLS.txt > Trichechus_manatus_latirostris.LS.fasta
xargs samtools faidx Tupaia_chinensis.faa < Tupaia_chinensis.faa.faiLS.txt > Tupaia_chinensis.LS.fasta
xargs samtools faidx Tursiops_truncatus.faa < Tursiops_truncatus.faa.faiLS.txt > Tursiops_truncatus.LS.fasta
xargs samtools faidx Urocitellus_parryii.faa < Urocitellus_parryii.faa.faiLS.txt > Urocitellus_parryii.LS.fasta
xargs samtools faidx Ursus_arctos_horribilis.faa < Ursus_arctos_horribilis.faa.faiLS.txt > Ursus_arctos_horribilis.LS.fasta
xargs samtools faidx Ursus_maritimus.faa < Ursus_maritimus.faa.faiLS.txt > Ursus_maritimus.LS.fasta
xargs samtools faidx Vicugna_pacos.faa < Vicugna_pacos.faa.faiLS.txt > Vicugna_pacos.LS.fasta
xargs samtools faidx Vombatus_ursinus.faa < Vombatus_ursinus.faa.faiLS.txt > Vombatus_ursinus.LS.fasta
xargs samtools faidx Vulpes_vulpes.faa < Vulpes_vulpes.faa.faiLS.txt > Vulpes_vulpes.LS.fasta
xargs samtools faidx Zalophus_californianus.faa < Zalophus_californianus.faa.faiLS.txt > Zalophus_californianus.LS.fasta
